"""Initial_migrations

Revision ID: 9a1bc678b688
Revises: 
Create Date: 2021-05-07 16:27:40.580031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1bc678b688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
                    sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('contacts', sa.String(length=80), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(length=120), nullable=False),
                    sa.Column('photo', sa.String(length=120), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('_id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('token_block_list',
                    sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('jti', sa.String(length=36), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('_id'),
                    sa.UniqueConstraint('jti')
                    )
    op.create_table('users',
                    sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('firstname', sa.String(length=80), nullable=False),
                    sa.Column('lastname', sa.String(length=80), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(length=120), nullable=False),
                    sa.Column('contacts', sa.String(length=120), nullable=False),
                    sa.Column('photo', sa.String(length=120), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('_id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('events',
                    sa.Column('_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('location', sa.String(length=80), nullable=False),
                    sa.Column('description', sa.String(length=250), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('available_places', sa.Integer(), nullable=False),
                    sa.Column('remaining_places', sa.Integer(), nullable=False),
                    sa.Column('start_at', sa.String(length=80), nullable=False),
                    sa.Column('end_at', sa.String(length=80), nullable=False),
                    sa.Column('image', sa.String(length=120), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('organizer_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['organizer_id'], ['organizers._id'], ),
                    sa.PrimaryKeyConstraint('_id')
                    )
    op.create_table('user_events',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['events._id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'event_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('token_block_list')
    op.drop_table('organizers')
    # ### end Alembic commands ###
